"""
SketchUp Ruby script generator.

Generates a .rb script that:
  1. Creates one Layer per floor level
  2. For each slab: adds a Face (polygon) then push/pulls it -200mm (downward)
  3. Assigns a material color per level
  4. Groups all slabs on the same level together
  5. Sets the active model units to mm

Usage: paste the generated script into SketchUp's Ruby Console (Window > Ruby Console).
"""

from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from datetime import datetime
from typing import Optional
import re
from shapely.geometry import MultiPolygon as _MultiPolygon


def _get_polygon(geom):
    if isinstance(geom, _MultiPolygon):
        return max(geom.geoms, key=lambda g: g.area)
    return geom


LEVEL_COLORS = [
    "#4FC3F7",  # light blue
    "#81C784",  # green
    "#FFB74D",  # orange
    "#F06292",  # pink
    "#CE93D8",  # purple
    "#80DEEA",  # cyan
    "#FFCC02",  # yellow
    "#FF8A65",  # deep orange
]


def _ruby_point(x_mm: float, y_mm: float, z_mm: float) -> str:
    """Format a SketchUp Geom::Point3d in mm units."""
    return f"Geom::Point3d.new({x_mm:.2f}.mm, {y_mm:.2f}.mm, {z_mm:.2f}.mm)"


def _sanitize_layer_name(name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_\-\. ]", "_", name)


def _level_key(page_index: int, ffl_m: Optional[float]) -> str:
    """Unique layer key combining page and FFL — prevents merge of same-FFL slabs on different floors."""
    ffl_str = f"{ffl_m:.3f}m" if ffl_m is not None else "Unknown"
    return f"P{page_index + 1:02d}_FFL_{ffl_str}"


def generate_ruby_script(
    slab_regions: list,
    output_path: str,
    thickness_mm: float = 200.0,
    generated_by: str = "Feeldx Slab Extractor",
) -> str:
    """
    Generate SketchUp Ruby script from a list of SlabRegion objects.
    slab_regions must have .real_polygon (Shapely Polygon in mm), .label, .ffl_m, .area_m2
    """
    lines = []
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Header
    lines += [
        "# ============================================================",
        f"# Generated by: {generated_by}",
        f"# Date: {now}",
        f"# Slabs: {len(slab_regions)}",
        f"# Thickness: {thickness_mm:.0f}mm (fixed)",
        "# Instructions: paste into SketchUp Ruby Console",
        "#   Window > Ruby Console > paste > Enter",
        "# ============================================================",
        "",
        "model = Sketchup.active_model",
        "model.start_operation('Import Slabs', true)",
        "",
        "entities = model.active_entities",
        "layers = model.layers",
        "materials = model.materials",
        "",
        "# Set model units to mm",
        "model.options['UnitsOptions']['LengthUnit'] = 4  # mm",
        "",
    ]

    # Compute page-level dominant FFL: most-frequently-assigned FFL across all slabs on a page.
    # This prevents layer explosion when individual slabs have different nearest-FFL values.
    page_ffl_counts: dict = defaultdict(Counter)
    for slab in slab_regions:
        if slab.ffl_m is not None:
            page_ffl_counts[slab.page_index][round(slab.ffl_m, 3)] += 1
    page_primary_ffl: dict = {
        page_idx: counts.most_common(1)[0][0]
        for page_idx, counts in page_ffl_counts.items()
        if counts
    }

    # Collect unique levels (one per page, keyed by page + dominant FFL)
    level_set = {}
    for slab in slab_regions:
        lvl = _level_key(slab.page_index, page_primary_ffl.get(slab.page_index))
        if lvl not in level_set:
            idx = len(level_set)
            color = LEVEL_COLORS[idx % len(LEVEL_COLORS)]
            level_set[lvl] = {"color": color, "index": idx}

    # Create layers and materials
    lines.append("# --- Layers & Materials ---")
    for lvl_name, info in level_set.items():
        safe_name = _sanitize_layer_name(lvl_name)
        lines.append(f'layer_{info["index"]} = layers.add("{safe_name}")')
        lines.append(
            f'mat_{info["index"]} = materials.add("mat_{safe_name}"); '
            f'mat_{info["index"]}.color = Sketchup::Color.new("{info["color"]}")'
        )
    lines.append("")

    # Create slab geometry
    lines.append("# --- Slab Geometry ---")
    for i, slab in enumerate(slab_regions):
        poly = _get_polygon(getattr(slab, "real_polygon", None))
        if poly is None or poly.is_empty:
            lines.append(f"# SKIPPED slab {slab.label}: no real_polygon")
            continue

        lvl = _level_key(slab.page_index, page_primary_ffl.get(slab.page_index))
        lvl_info = level_set[lvl]
        z_mm = slab.ffl_mm if slab.ffl_mm is not None else 0.0
        area_txt = f"{slab.area_m2:.2f}m²" if slab.area_m2 > 0 else "?"
        safe_label = _sanitize_layer_name(slab.label)

        # Exterior ring coords
        coords = list(poly.exterior.coords)
        if len(coords) < 3:
            lines.append(f"# SKIPPED slab {slab.label}: too few points")
            continue

        # SketchUp add_face needs CCW order when viewed from above
        # Shapely exterior is CCW by default (positive area)

        lines += [
            "",
            f"# Slab {i + 1}: {slab.label} | {lvl} | Area: {area_txt}",
            f"begin",
            f"  pts_{i} = [",
        ]
        for x, y in coords[:-1]:  # exclude closing duplicate
            lines.append(f"    {_ruby_point(x, y, z_mm)},")
        lines[-1] = lines[-1].rstrip(",")  # remove trailing comma on last point
        lines += [
            f"  ]",
            # Each slab gets its own Group so SketchUp cannot auto-merge shared edges,
            # which previously caused "reference to deleted DrawingElement" errors.
            f"  grp_{i} = entities.add_group",
            f"  face_{i} = grp_{i}.entities.add_face(pts_{i})",
            f"  if face_{i} && face_{i}.valid?",
            f"    face_{i}.pushpull(-{thickness_mm:.0f}.mm)",
            f"    grp_{i}.layer = layer_{lvl_info['index']}",
            f"    grp_{i}.material = mat_{lvl_info['index']}",
            f"    grp_{i}.name = '{safe_label}'",
            f"  end",
            f"rescue => e",
            f"  puts 'Error creating slab {safe_label}: ' + e.message",
            f"end",
        ]

    # Finalize
    lines += [
        "",
        "# --- Finalize ---",
        "model.commit_operation",
        "Sketchup.active_model.active_view.zoom_extents",
        f"puts 'Done! {len(slab_regions)} slabs imported.'",
    ]

    script_content = "\n".join(lines)
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(script_content)

    return script_content


def generate_slab_csv(slab_regions: list, output_path: str) -> str:
    """Export slab data as CSV for reference."""
    import csv
    rows = []
    for slab in slab_regions:
        rows.append({
            "ID": slab.id,
            "Label": slab.label,
            "FFL_m": slab.ffl_m if slab.ffl_m is not None else "",
            "FFL_mm": slab.ffl_mm if slab.ffl_mm is not None else "",
            "Thickness_mm": 200,
            "Area_m2": f"{slab.area_m2:.3f}" if slab.area_m2 > 0 else "",
            "Page": slab.page_index + 1,
            "Source": slab.source,
        })

    with open(output_path, "w", newline="", encoding="utf-8") as f:
        if rows:
            writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
            writer.writeheader()
            writer.writerows(rows)

    return output_path
